### PR TITLE
Mmap test

### PR DESCRIPTION
**Pull request by ladislav-zezula**

### CODE REVIEW

**Comment by glebm** [comment]
This does not build (<https://github.com/diasurgical/devilutionX/pull/1314>). E.g. for a 3ds build we get:

```
src/FileStream.cpp:641:77: error: 'munmap' was not declared in this scope
         munmap(pStream->Base.Map.pbFile, (size_t )pStream->Base.Map.FileSize);
```

**Comment by glebm** [comment]
I also don't quite understand this fix. Even with the compilation error fixed, won't it still try to `BaseMap_Open`, only for it to fail?

**Comment by ladislav-zezula** [comment]
I fixed 'munmap` as well: https://github.com/ladislav-zezula/StormLib/pull/214

> I also don't quite understand this fix. Even with the compilation error fixed, won't it still try to BaseMap_Open, only for it to fail?

Yes.

Need to say, the only way to get the map code to actually be called is if you do this:
```
FileStream_OpenFile("map:\\Path\\File.ext", ...)
```
In most of the cases, it won't be used anyway. Just forget it.

**Comment by glebm** [comment]
Ah OK, thanks!

**Pull request merged**
