### PR TITLE
Compile fixes for Unix C applications

### PR DESCRIPTION
**Pull request by pali**
* Make header files compatible with both C and C++
* Get variables from ZLIB + BZip2 packages
* Allow to use WITH_LIBTOMCRYPT on any non-windows system

### CODE REVIEW

**Comment by Fylwind** [comment]
> Use C comments `/* */` which are compatible with C and C++ instead C++ only `//`.

`//` works just fine on C99 or higher, and even for compilers that don't have full C99 support, the new comment syntax is still supported anyway (e.g. MSVC).

**Comment by pali** [comment]
Yes, but it does not work with ANSI C strict mode.

It is compatible with ANSI C++, but not with ANSI C...

**Comment by ladislav-zezula** [comment]
Cmon people it's 21 century, forget about pure C. The library contains classes as well, who needs pure C? The C++ comments worker even when I was young, which was 20 years ago.

**Comment by pali** [comment]
In C++ yes, in C not.

Just take gcc-4.8 and enable pedantic mode (which do strict checking). It refuse to compile this example code:
```
// test comment
int main() {
        return 0;
}
```
Output is:
```
$ gcc-4.8 -pedantic -Werror test.c 
test.c:1:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // test comment
 ^
```

gcc-4.8 has default mode ISO C90 if you do not specify other. And almost all applications are compiling with default gcc flags -- and not changing -std=

**Comment by pali** [comment]
Anyway, other two CMakeLists.txt patches are needed for compilation on other Unix systems. Those cannot be workarounded by customs gcc flags. Otherwise we got linker errors, because libs are not properly specified:
```
/usr/lib/libstorm.so: undefined reference to `BZ2_bzDecompress'
/usr/lib/libstorm.so: undefined reference to `deflateInit2_'
/usr/lib/libstorm.so: undefined reference to `md5_process'
/usr/lib/libstorm.so: undefined reference to `BZ2_bzCompressInit'
/usr/lib/libstorm.so: undefined reference to `BZ2_bzCompressEnd'
/usr/lib/libstorm.so: undefined reference to `sha1_desc'
/usr/lib/libstorm.so: undefined reference to `rsa_sign_hash_ex'
/usr/lib/libstorm.so: undefined reference to `rsa_import'
/usr/lib/libstorm.so: undefined reference to `rsa_free'
/usr/lib/libstorm.so: undefined reference to `register_hash'
/usr/lib/libstorm.so: undefined reference to `deflate'
/usr/lib/libstorm.so: undefined reference to `ltc_mp'
/usr/lib/libstorm.so: undefined reference to `find_hash'
/usr/lib/libstorm.so: undefined reference to `deflateEnd'
/usr/lib/libstorm.so: undefined reference to `crc32'
/usr/lib/libstorm.so: undefined reference to `sha1_process'
/usr/lib/libstorm.so: undefined reference to `base64_decode'
/usr/lib/libstorm.so: undefined reference to `inflate'
/usr/lib/libstorm.so: undefined reference to `md5_init'
/usr/lib/libstorm.so: undefined reference to `rsa_verify_hash_ex'
/usr/lib/libstorm.so: undefined reference to `inflateInit_'
/usr/lib/libstorm.so: undefined reference to `BZ2_bzDecompressEnd'
/usr/lib/libstorm.so: undefined reference to `BZ2_bzDecompressInit'
/usr/lib/libstorm.so: undefined reference to `inflateEnd'
/usr/lib/libstorm.so: undefined reference to `BZ2_bzCompress'
/usr/lib/libstorm.so: undefined reference to `crypt_argchk'
/usr/lib/libstorm.so: undefined reference to `md5_done'
/usr/lib/libstorm.so: undefined reference to `sha1_done'
/usr/lib/libstorm.so: undefined reference to `md5_desc'
/usr/lib/libstorm.so: undefined reference to `sha1_init'
/usr/lib/libstorm.so: undefined reference to `adler32'
/usr/lib/libstorm.so: undefined reference to `ltm_desc'
```

**Comment by ladislav-zezula** [comment]
I have conflict there, because another Linux guy made changes in it.
Could you please re-do your changes into the latest CMakeLists.txt?

**Comment by pali** [comment]
Rebased, hope it is correct...

**Comment by ladislav-zezula** [comment]
Merged.

**Pull request closed without merging**
