### PR TITLE
Added `#pragma once` into the top of `pklib.h`.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
No. Please, do not do any beatifying just for the beatifying.

**Comment by KOLANICH** [comment]
`#pragma once` is not so beautifying, but also an optimization.

**Comment by ladislav-zezula** [comment]
Could you please put the `#pragma once` after the comment, preferably to line 13?

**Comment by KOLANICH** [comment]
I can, the majority of compilers now support it to be not on the first line of a file. I'll do it on Monday.

**Comment by KOLANICH** [comment]
Done.

**Comment by ladislav-zezula** [comment]
Merged. Thanks for the contribution.

**Pull request merged**
