### PR TITLE
Added inclusion of `stddef.h` into `pklib.h`

### PR DESCRIPTION
**Pull request by KOLANICH**
(needed for 540d5dada1970bb1a4d01834a843c28634c21a49, but will be needed later in the header).

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
No. Please, do not do any beatifying just for the beatifying.

**Comment by KOLANICH** [comment]
It's not beautifying.

**Comment by ladislav-zezula** [comment]
The include was not there before; is there any reason why do you need them there now?

**Comment by KOLANICH** [comment]
1. I have created a fork of this lib. I mean not `StormLib`, but `pklib`. A standalone one, that can be used without `StormLib`.
2. It fails to compile without that include.
3. While that include can be put into the `.c` file, in my fork I'm extending this lib public API with some functions telling how much memory should be allocated for internal structs. If buffers sizes are changed anywhen in future, using the sizes would allow to allocate the needed amount of memory and even access com-ressor and decompressor objects' internal state. I'd prefer to upstream [that code](https://github.com/KOLANICH-libs/StormLib/tree/dynamically_discoverable_sizes) too. Those functions have `size_t` in signatures, so that's why I have added the inclusion into the header.

**Comment by ladislav-zezula** [comment]
Is the `size_t` in `GenDecodeTabs()` the only reason why the standalone pklib won't compile?

**Comment by KOLANICH** [comment]
No. As I have said, in my fork I has introduced a few structs with `size_t` fields and a few functions giving access to these structs (though I guess using `size_t` is a poor decision, I should have used the types with exact count of bits, like `uint16_t`).

The commit I have referenced was a wrong one. I gonna investigate which one is right on Monday.

BTW: my standalone fork is https://github.com/implode-compression-impls/pklib

**Comment by KOLANICH** [comment]
This addition shouldn't be a part of this separate PR. Strangely a quite minor refactoring has triggered the compile error. I need to figure out why.

**Pull request closed without merging**
