### PR TITLE
Add support for deb and rpm generation with CPack

### PR DESCRIPTION
**Pull request by cen1**
This configuration allows us to generate DEB and RPM packages with CPack. Usage:
cmake -G "Unix Makefiles" -B./build -H./
cd build
make
cpack -G "DEB"
cpack -G "RPM"

`rpm -qip StormLib-9.20-Linux.rpm` output:

> Name        : stormlib
> Version     : 9.20
> Release     : 1
> Architecture: x86_64
> Install Date: (not installed)
> Group       : StormLib
> Size        : 594734
> License     : /home/cen/git/StormLib/LICENSE
> Signature   : (none)
> Source RPM  : stormlib-9.20-1.src.rpm
> Build Date  : čet 30 jun 2016 13:31:51 CEST
> Build Host  : local.xpam.pl
> Relocations : /usr 
> Vendor      : Ladislav Zezula
> URL         : http://www.zezula.net/en/mpq/stormlib.html
> Summary     : MPQ manipulation library
> Description :
> This is official repository for the StomLib library, an open-source project that can work with Blizzard MPQ archives.

`dpkg -I StormLib-9.20-Linux.deb` output:

> new debian package, version 2.0.
>  size 198296 bytes: control archive=426 bytes.
>      250 bytes,    11 lines      control              
>      176 bytes,     3 lines      md5sums              
>  Package: stormlib
>  Version: 9.20
>  Section: libs
>  Priority: optional
>  Architecture: amd64
>  Depends: zlib1g,bzip2
>  Homepage: http://www.zezula.net/en/mpq/stormlib.html
>  Installed-Size: 1609
>  Maintainer: imbacen@gmail.com
>  Description: MPQ manipulation library

Local install example:
Using gdebi for auto dependency resolve (you can use dpkg but then you need to manually install dependencies): `sudo gdebi StormLib-9.20-Linux.deb`
Using dnf on Fedora: `dnf install StormLib-9.20-Linux.rpm`

Library is installed in `/usr/lib`. libstorm.so -> libstorm.so.9 -> libstorm.so.9.20.0

I am personally hosting repositories on my server for anyone who wants to use them. For Debian jessie:
 1. To /etc/apt/sources.list add:
#apt.xpam.pl
deb http://apt.xpam.pl/ jessie main

 2. Add GPG key:
wget -qO - http://apt.xpam.pl/xpam.pl-pubkey.asc | sudo apt-key add -

 3. Update and install:
sudo apt-get update
sudo apt-get install stormlib

Public RPM repo is on my todo list and will be hosted soon (probably sth. like rpm.xpam.pl)

Additional info: I seperated the VERSION property into major, minor and patch vars so I could reuse the variables in CPack configuration. Old value was 9.0.0 while latest github release is on 9.20 so I lifted that aswell. Due to chicken and egg problem the actual produced packages do not contain the 9.20 build but master build. For proper version generation version must be lifted! Afaik there were no breaking changes so it doesn't matter much anyway.

### CODE REVIEW

**Comment by cen1** [comment]
Yum examples:
In `/etc/yum.repos.d/rpm.xpam.pl.repo` add

[rpm.xpam.pl]
name = rpm.xpam.pl
baseurl = https://rpm.xpam.pl

Import key and install:
rpm --import https://rpm.xpam.pl/stormlib-pubkey.asc
yum install stormlib

Adding repo to dnf:
dnf config-manager --add-repo https://rpm.xpam.pl


By default CPack generated rpm is not signed. While yum by default does not check signatures, dnf does and install will fail. In order to sign the rpm:
`gpg2 --full-gen-key`
In `~/.rpmmacros` add: `%_gpg_name YourName <your@email>`
`rpmsign --addsign StormLib-9.20-Linux.rpm`
g`pg --armor --export your@email > stormlib-pubkey.asc`
`rpm --import stormlib-pubkey.asc`
`rpm --checksig StormLib-9.20-Linux.rpm` (must return OK)

The rpm is now signed and can be installed after public key is imported on the client machine.

**Comment by cen1** [comment]
Header files are installed in `/usr/include`. Unfortunately the projects require including like `#include <stormlib/StormLib.h>` so the actual install directory has to be `/usr/include/stormlib`. I did not find how to change that with CPack but I am waiting for an answer on Cmake mailing list. I'll add the patch to this branch once I figure it out.

**Comment by pali** [comment]
Hi! StormLib is already packaged in Debian stretch, see: https://packages.debian.org/source/stretch/stormlib

**Comment by cen1** [comment]
Nice, I didn't know that! I guess it would be possible to use testing repos in jessie and just install stormlib from it: `apt-get -t testing install stormlib`? Not sure what other implications are for adding testing repos to stable releases.

Is there any information if stormlib will be included in the next stable release or will it stay in testing only?

**Comment by wheybags** [comment]
The testing release will become the stable release iirc, so it should be in
automatically

**Comment by cen1** [comment]
Header files now install to /usr/include/stormlib. GHost++ builds out of the box.

**Comment by pali** [comment]
Please do not change such thing like path where header files will be installed. You are going to break packaging systems and also existing applications which uses current version of stormlib project.

**Comment by pali** [comment]
Until now it uses "#include <StromLib.h>" and not "#include <stormlib/StormLib.h>".

**Comment by cen1** [comment]
This is the problem I am trying to solve, example of ghost++ code: https://github.com/OHSystem/OHSystem/blob/master/ghost/src/map.cpp line 31. Can we install in both locations or is there another solution?

**Comment by pali** [comment]
And can be ghost++ compiled with "upstream" code?
Yes --> no change is needed.
No --> it is ghost++'s problem and ghost++ should be fixed.

**Comment by pali** [comment]
Now I see that ghost++ uses its own stormlib version, so ghost++ is not designed to use upstream stormlib. That means ghost++ have to fix that itself.

**Comment by cen1** [comment]
It compiles fine with upstream, I guess the prefix was added when the project started for whatever reason. Since I never used any other project that uses stormlib I though that's the standard way. I'll revert the commit. It's a trivial problem to fix in ghost code.

**Pull request merged**
