### PR TITLE
fix cmake dependency and move headers to include

### PR DESCRIPTION
**Pull request by Lectem**
Having shared libraries built by default isn't a good thing with cmake, especially since no import .lib is created on MSVC. I changed it so that it uses the official CMake variable BUILD_SHARED_LIBS.
Projects relying on this CMakeLists.txt to use Stormlib as a dependency would fail to link with visual (since no .lib is generated), so I made it so that you can use target_link_libraries(yourtarget stormlib) without any worries by default.

I moved the 2 required headers to the include folder, the reason is that otherwise libraries linking it would have an include folder path polluted with stormlib dependencies (which could conflict with other versions). It also make it
I updated all the build files except StormLib_vs08 , but couldn't test premake/osx.

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
When I am trying to make it under Linux, I get error "Unknown CMake command - target_include_directories

**Comment by Lectem** [comment]
Oh, what version of CMake is this ?
I think this command was added in CMake 3, I forgot to check the cmake_minimum_required VERSION...
It should be bumped to cmake_minimum_required(VERSION 3.0) or we could use set_target_properties(${LIBRARY_NAME} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES include/).
It's up to you if you want to enforce a newer version of cmake or not, but for the last 1-2 years Linux distributions have been using CMake 3+ in their package repositories (at least Ubuntu/Debian do).

**Comment by ladislav-zezula** [comment]
It is KDevelop 4.3.1, dunno which version of CMAke it is.
I used INCLUDE_DIRECTORIES and it works. However, I NOP-ed all changes made by you in CMakeLists.txt
See commit 3c8cc59c40509f7a1476bd9092e30da3365c58c6.
Can you please re-check CMakeLists.txt?

**Comment by ladislav-zezula** [comment]
I fixed CMakeLists.txt and also reverted the include directory. While I generally like that change you made (from the point of view of code niceness), I don't really see any value added. People have been building StormLib for years, if it worked before, it must also work now.

Althought I removed a few includes that weren't really needed.

**Comment by Lectem** [comment]
KDevelop will simply use the cmake installed on your system, to update it you can check your package manager or directly download it from https://cmake.org/download/ however I'd understand if you want to keep compatibility with older CMake versions.

I was talking about the INCLUDE_DIRECTORIES target property not the command though. The problem with the include_directories() is that it is global and affects all targets, even those which don't link the library. That's why *modern* cmake uses per target properties (see https://schneide.wordpress.com/2016/04/08/modern-cmake-with-target_link_libraries/)
Thing is, I just got confirmation that only INTERFACE_* are propagated when linking, and that it's a cmake 3+ only feature, so we can't really use it with 2.6.
This is still better than before though, and if you want to keep cmake 2.6 compatibility then I can adapt the other changes (BUILD_SHARED_LIB and the definition of D__STORMLIB_NO_AUTO_LINK__), just let me know what you prefer.

**Comment by ladislav-zezula** [comment]
I fixed CMakeLists.txt and also reverted the include directory. While I generally like that change you made (from the point of view of code niceness), I don't really see any value added. People have been building StormLib for years, if it worked before, it must also work now.

Althought I removed a few includes that weren't really needed, so it was still good for something.

**Comment by Lectem** [comment]
The added value is to be able to use it more easily in CMake projects, some people even redefined the whole library CMakeLists.txt like this : https://github.com/wheybags/freeablo/blob/master/extern/CMakeLists.txt 
What I wanted to do was to make it as painless as `add_subdirectory(StormLib)` + `target_link_libraries(mytarget StormLib)`. While I can do this right know, I also need to add 

    set(WITH_STATIC ON CACHE BOOL "dont build shared StormLib")

before calling add_subdirectory
and then for every target using it

    target_include_directories(target PUBLIC some/path/to/StormLib/src)
    target_compile_definitions(target PUBLIC -D__STORMLIB_NO_AUTO_LINK__)

so that it builds with MSVC.

Note that the other alternative would require to fix the install script and provide a FindFmtLib.cmake so that people can use `find_package`.

Also the the point about not having bzip2 lzma zlib or other subdirectories in the include path still holds, as I said it could cause compatibility problems. (unless we choose to fix the install script, in which case it wouldn't be a problem)
I understand that this is mainly a CMake related problem, but I still think it requires a solution.

Note : you forgot to move the headers back to src/

**Comment by ladislav-zezula** [comment]
Headers added back.

Ok, let's try to make a compromise. I'll try to go through your CMakeLists.txt and try to undestand the consequences. As I am not a Linux programmer (except for occasional building of the testprogram), there's lots of things that are not quite clear to me.

**Comment by Lectem** [comment]
If you want an example of how I use dependencies in my project you can check https://github.com/Lectem/boilerplate/
Basically I add use add_subdirectory to include all external dependencies, and then just link them to the targets (modules, projects, libs, whatever) that need it. When using target_* to add a property with PUBLIC or INTERFACE on a target (here it would be StormLib), anything that will link this target will also get this property. (that's what is explained in https://schneide.wordpress.com/2016/04/08/modern-cmake-with-target_link_libraries and called transitive properties ).
This helps in scenarios where you have a lot a small subprojects that link each other. For example : 
- libA uses Stormlib zlib
- libB uses libA
- libC uses libjpeg
- executable links libB and libC, but will get information for includes/defines automatically for libjpeg,Stormlib and zlib as those are target with PUBLIC/INTERFACE properties.

This way you don't have to list/update every single library usage for executable if libA/libB/libC changes.

This system is described here in the official doc : https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html

(Because I'm unsure of what CMakeLists.txt you were talking about, the one I linked from freeablo is obviously not doing the good thing)

If you need help or have any question, feel free to send me a mail or contact on twitter (those are in my profile)

**Pull request merged**
