### PR TITLE
FileStream: Add a define for mmap

### PR DESCRIPTION
**Pull request by glebm**
The following platforms do not have full mmap support currently:
Amiga, Switch, 3DS, and Vita

These platforms are added in #206.

/cc @AJenbo

### CODE REVIEW

**Comment by AJenbo** [comment]
Don't forget this also delayed the port to https://github.com/SerenityOS/serenity

**Comment by ladislav-zezula** [comment]
With the commit https://github.com/ladislav-zezula/StormLib/commit/ce159e90bca94be3c9050fe467d497cfcbe759a8, the new platforms will also define `STORMLIB_MAC`, which should solve the problem.

Could you please check?

**Comment by glebm** [comment]
I'm not sure how that commit solve this problem. macOS has mmap support, these plaforms do not!

**Comment by glebm** [comment]
I guess the `STORMLIB_HAVE_MMAP` define can now be moved to `StormPort.h`

**Comment by ladislav-zezula** [comment]
Fixed: https://github.com/ladislav-zezula/StormLib/pull/209

**Pull request closed without merging**
